# Generated by Django 2.1.2 on 2019-09-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_full_name', models.CharField(max_length=100)),
                ('book_simple_name', models.CharField(max_length=32)),
                ('book_image', models.FileField(max_length=1024, upload_to='')),
                ('book_create_time', models.DateTimeField()),
                ('book_last_update_time', models.DateTimeField()),
                ('book_absract', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BookChacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chacter', models.BigIntegerField()),
                ('chacter_name', models.CharField(max_length=100)),
                ('chacter_content', models.TextField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookChacterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chacter', models.BigIntegerField()),
                ('chacter_image', models.FileField(max_length=1024, upload_to='')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Book')),
            ],
        ),
    ]
