# Generated by Django 2.1.2 on 2019-09-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190919_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_last_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
